import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Sora } from "next/font/google";
import { BrowserView, MobileView } from "react-device-detect";
import "./globals.css";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LASU - Regaleon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <BrowserView>
          <main>{children}</main>
          <Toaster />
        </BrowserView>
        <MobileView>
          <div></div>
        </MobileView>
      </body>
    </html>
  );
}
